// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slpmtzwqakcczbgaaaie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNscG10endxYWtjY3piZ2FhYWllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzM5OTUsImV4cCI6MjA2NTgwOTk5NX0.JkWaGfd8VN8giSi3AWy9JSqMtnKYQw1BjZXjNEjbMnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);